In [1]:
import tensorflow as tf
import numpy as np

In [35]:
#make constant

t = tf.constant([[[[9, 10, 11, 12]],
                   [[13, 14, 15, 16]]]])

t1=tf.constant([[[1, 2, 3, 4], [5, 6, 7, 8]],
              [[17, 18, 19, 20], [21, 22, 23, 24]]])


print(t.ndim)
print(t.shape)

print(t1.ndim)
print(t1.shape)



4
(1, 2, 1, 4)
3
(2, 2, 4)


In [29]:
#reduce sum
print(tf.reduce_sum(t1,axis=0))

print(tf.reduce_sum(t1,axis=1))

print(tf.reduce_sum(t1,axis=2))

tf.Tensor(
[[18 20 22 24]
 [26 28 30 32]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 6  8 10 12]
 [38 40 42 44]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[10 26]
 [74 90]], shape=(2, 2), dtype=int32)


In [31]:
#broadcasting
m1=tf.constant([3,6])
m2=tf.constant([10])
print(m1+m2)

tf.Tensor([13 16], shape=(2,), dtype=int32)


In [42]:
#squeeze
print(t.shape)
print(tf.squeeze(t).shape)
print(tf.squeeze(t,axis=0).shape)
#print(tf.squeeze(t,axis=1).shape) ##ERROR
print(tf.squeeze(t,axis=2).shape)

(1, 2, 1, 4)
(2, 4)
(2, 1, 4)
(1, 2, 4)


In [61]:
#expand
print(t.shape)
print(tf.expand_dims(t,[1]).shape)
print(tf.expand_dims(t,[3]).shape)
print(tf.expand_dims(t,[4]).shape)
#print(tf.expand_dims(t,[5]).shape) #Error!

(1, 2, 1, 4)
(1, 1, 2, 1, 4)
(1, 2, 1, 1, 4)
(1, 2, 1, 4, 1)


In [63]:
tf.cast(t1 , tf.float32)

<tf.Tensor: id=143, shape=(2, 2, 4), dtype=float32, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float32)>